name: Deploy Frontend Dev

on:
  push:
    branches: [ "develop" ]

defaults:
  run:
    working-directory: frontend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./frontend/package-lock.json"
    
    - name: Install
      run: npm install
      
    - name: Build
      run: npm run build-dev
      
    - name: Deploy
      run: curl ${{ secrets.FE_DEV_DEPLOY_REQUEST_URL }}
      
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
